### ISSUE TITLE
Issue with joblib import from sklearn.

### ISSUE THREAD

**Issue by saroudant** [idc9/py_jive#6]
Dear @idc9,

Thanks a lot for this very nice package. I used it last year for one project and was very happy with it.
I try to reproduce my results from last year but a problem occurred in a meantime: sklearn has changed its import policy ([more info here](https://github.com/scikit-learn/scikit-learn/pull/13531/files#r276153496)). Joblib cannot be imported from sklearn.externals anymore.
As a direct result, the import command (from jive.AJIVE import AJIVE) prompts the following error:
---------------------------------------------------------------------------

> 
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-b1aa441ed9c4> in <module>
>       5 import seaborn as sns
>       6 from sklearn.preprocessing import StandardScaler
> ----> 7 from jive.AJIVE import AJIVE
>       8 from jive.PCA import PCA
>       9 
> 
> ~/.conda/envs/trickle_down/lib/python3.7/site-packages/jive/AJIVE.py in <module>
>       3 from scipy.sparse import issparse
>       4 from copy import deepcopy
> ----> 5 from sklearn.externals.joblib import load, dump
>       6 import pandas as pd
>       7 
> 
> ModuleNotFoundError: No module named 'sklearn.externals.joblib'
> 
> This is a very quick fix (import directly from joblib), just wanted to point this out.
> 

Best,
Soufiane

**Comment by idc9** [comment]
Thanks for pointing this out and I've fixed this issue (currently available on the github version of the code). I also just released a new version of AJIVE code here: https://github.com/idc9/mvdr.

**Comment by saroudant** [comment]
Great, thanks ! I will take a look to the new version of AJIVE. Is it as stable as the previous version yet ?
